delete from XIANAV3.dbo.tailoring_examine where id>0
delete from XIANAV3.dbo.tailoring_examine_fabric_record where id>0
delete from XIANAV3.dbo.tailoring_examine_no where id>0
delete from XIANAV3.dbo.tailoring_examine_plan where id>0
delete from XIANAV3.dbo.tailoring_fabric_consume where id>0
delete from XIANAV3.dbo.tailoring_fabric_left where id>0
delete from XIANAV3.dbo.tailoring_fabric_record where id>0
delete from XIANAV3.dbo.tailoring_order where id>0
delete from XIANAV3.dbo.tailoring_plan where id>0
delete from XIANAV3.dbo.tailoring_recovery_record where id>0
delete from XIANAV3.dbo.tailoring_detail where id>0
delete from XIANAV3.dbo.tailoring_spreading where id>0
delete from XIANAV3.dbo.tailoring_task where id>0
delete from XIANAV3.dbo.tailoring_task_plan where id>0
